runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:0ZfjHYW9pW4lBl0TvLPlG5VNrQ+b8oz5WeTpEZnzvj8=
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: umang
  DB_USERNAME: umang
  DB_PASSWORD: umang
  DB_SOCKET: "/cloudsql/ipingdatalabs:asia-south1:test"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "ipingdatalabs:asia-south1:test"